### ISSUE TITLE
Add fields to the table

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sparrow-mrb3-js#10]
Each table should add the following fields:

- [ ] Basin Area

- [ ] Title/Name (if available)

- [ ] Upstream Area (this may be for just catchments?)

**Comment by esmyers** [comment]
Is this for the new table that Tonia created, or for the existing table in Sparrow Tennessee?

**Comment by troddick** [comment]
I'm not clear on where this information would come from. 
The information I'm showing is coming from the information displayed in the Chart. 
The lobipanel has the Title for the chart and the table. What other title would I use within just the table?

**Comment by HansVraga** [comment]
This was suggested by Dave, I'm not even certain of the feasibility.
@esmyers do you know if the Basin Area, Title/Name, and Upstream Area fields exist for all polygons? If not all, do they exist for catchments?

**Comment by esmyers** [comment]
Upstream area only exists for catchments.  That is the DEMTAREA field.

I think catchment is the only field in this dataset that has a name we would need to access instead of an ID  that would be the PNAME field in catchments.  We have to use the MRB_ID field to reference data in the app though, since the PNAMEs are not necessarily unique.

If by 'Basin Area' we are talking about the area of each polygon displayed, that information is available for all layers.  Those fields are in each layer as {AreaUnit}_AREA

**Comment by troddick** [comment]
@HansVraga , @esmyers 
I'm still slightly hazy on this one. Is this a 2-part process?

@esmyers needs to include extra fields in the response
then I need to add these 3 fields to the table?

**Comment by HansVraga** [comment]
@troddick  I don't think it's a 2 part process. For all Layers, add {AreaUnit}_AREA to the table. 
For Catchments, add the DEMTAREA field and the PNAME field. (put PNAME at the front of the table).

I'll leave it to you and @esmyers to determine the best way to pull in these fields/determine if you're looking at catchments.

**Comment by troddick** [comment]
done
